#!/bin/bash

# Build docker image
git clone https://github.com/spectosi/dokku-pg94-dockerfiles.git /tmp/dokku-pg94-dockerfiles
docker build -q=true -t specto/dokku-pg94 /tmp/dokku-pg94-dockerfiles
rm -rf /tmp/dokku-pg94-dockerfiles
